spring:
    datasource:
        username: sudofridgigo
        password: dwt-kcg7TBK_qgw4ved
        url: jdbc:mysql://localhost:3306/rezeptdatenbank
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

